init:
 - appveyor version
 #- ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: sw_vers
 - sh: whoami
 - sh: ifconfig
 
test_script:
 - sh: which dotnet
 - sh: dotnet --version
 - sh: ls ~/Qt/latest/clang_64
 - sh: ls ~/Qt/5.15/clang_64
 - sh: ls ~/Qt/6.2/macos
 - sh: ls ~/Qt/6.5/macos
 - sh: ls ~/Qt/6.6/macos
 - sh: curl --version
 - sh: ls -al $HOME
 - sh: df -h
 - sh: ls -al /Applications
 - sh: git --version
 - sh: git lfs version
 - sh: hg --version
 - sh: svn --version
 - sh: xcodes version
 - sh: xcodes list | grep Installed
 - sh: xcodes runtimes | grep Installed
 - sh: brew --version
 - sh: brew list
 - sh: |
      for t in curl mercurial subversion git git-lfs; do
          brew info "$t" | head -1
      done
 - sh: brew list --cask
 - sh: |
      for t in powershell fastlane adoptopenjdk10 adoptopenjdk12 adoptopenjdk8 adoptopenjdk11 adoptopenjdk13 adoptopenjdk9 adoptopenjdk14 adoptopenjdk15; do
          brew info --cask "$t" | head -1
      done
 - sh: javac -version
 - sh: env|grep JAVA || true
 - sh: nvm --version
 - sh: nvm list
 - sh: rvm --version
 - sh: rvm list
 - sh: gvm version
 - sh: gvm list
 - sh: cat $HOME/versions.log
 - sh: echo "test" > test.txt 
 #- sh: osascript -e 'tell application "Finder" to set current view of container window to icon view'
 
build: off

artifacts:
- path: test.txt

on_failure:
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
