init:
 - appveyor version
 - ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: sw_vers
 
test_script:
 - sh: xcversion selected
 - sh: xcversion list |grep '(installed)'
 - sh: xcversion simulators |grep '(installed)'
 - sh: xcversion
 - sh: xcversion list
 - sh: xcversion simulators
 - sh: javac -version
 - sh: env|grep JAVA || true
 - sh: nvm --version
 - sh: nvm list
 - sh: rvm --version
 - sh: rvm list
 - sh: gvm version
 - sh: gvm list
 - sh: cat $HOME/versions.log
 
build: off
